name: "WhereIsIt"
version: "0.1.0"
slug: "whereisit"
description: "Physical storage management for Home Assistant"
url: "https://github.com/german/whereisit"
startup: application
arch:
  - aarch64
  - amd64
  - armv7
init: false
map:
  - config:rw
options: {}
schema: {}
ingress: true
ingress_port: 8000
ingress_entry: /
panel_icon: mdi:box-variant
